/**
 * Builds the promo page from src/page.html.
 *
 * The page is themed by the editor's own palettes, so rather than copying hex
 * values by hand we read them out of src/styles/base.css and themes.css and
 * emit one self-contained token block per theme. Change a theme in the app and
 * re-running this keeps the site honest.
 *
 *   node website/build.mjs
 *
 * Outputs:
 *   website/index.html     standalone page (images inlined, opens from disk)
 *   website/artifact.html  same page as a fragment, for publishing
 */
import { readFileSync, writeFileSync, readdirSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const repo = join(here, "..");

const LIGHT = ["paper", "github-light", "solarized-light", "snow"];
const DARK = ["midnight", "nord", "dracula", "gruvbox", "solarized-dark"];

/** Parses `--name: value;` pairs out of a CSS block body. */
function declarations(body) {
  const out = new Map();
  for (const m of body.matchAll(/(--[\w-]+)\s*:\s*([^;]+);/g)) {
    out.set(m[1], m[2].trim());
  }
  return out;
}

/** Finds the block for a selector and returns its declarations. */
function block(css, selector) {
  const at = css.indexOf(selector);
  if (at < 0) throw new Error(`selector not found: ${selector}`);
  const open = css.indexOf("{", at);
  const close = css.indexOf("}", open);
  return declarations(css.slice(open + 1, close));
}

// Working copies on Windows are CRLF; normalise so selectors match.
const CRLF = new RegExp(String.fromCharCode(13) + String.fromCharCode(10), "g");
const read = (p) => readFileSync(p, "utf8").replace(CRLF, String.fromCharCode(10));

const baseCss = read(join(repo, "src/styles/base.css"));
const themeCss = read(join(repo, "src/styles/themes.css"));

const light = block(baseCss, ':root,\n:root[data-theme="light"]');
const dark = block(baseCss, ':root[data-theme="dark"]');

const overrides = new Map();
for (const m of themeCss.matchAll(/:root\[data-palette="([\w-]+)"\]\s*\{([^}]*)\}/g)) {
  overrides.set(m[1], declarations(m[2]));
}

const render = (map) =>
  [...map].map(([k, v]) => `  ${k}: ${v};`).join("\n");

/** A theme's full token set: the light or dark base, plus its own overrides. */
function merged(id, mode) {
  const out = new Map(mode === "dark" ? dark : light);
  for (const [k, v] of overrides.get(id) ?? []) out.set(k, v);
  out.set("color-scheme", mode);
  return out;
}

const parts = [
  "/* Generated by website/build.mjs from the editor's own stylesheets. */",
  `:root {\n${render(light)}\n}`,
  // Un-stamped viewers (the "system" default) only have prefers-color-scheme.
  `@media (prefers-color-scheme: dark) {\n  :root:not([data-theme="light"]):not([data-palette]) {\n${render(
    dark,
  )
    .split("\n")
    .map((l) => "  " + l)
    .join("\n")}\n  }\n}`,
  `:root[data-theme="dark"]:not([data-palette]) {\n${render(dark)}\n}`,
  `:root[data-palette="onionskin"] {\n${render(merged("onionskin", "light"))}\n}`,
  `:root[data-palette="carbon"] {\n${render(merged("carbon", "dark"))}\n}`,
  ...LIGHT.map((id) => `:root[data-palette="${id}"] {\n${render(merged(id, "light"))}\n}`),
  ...DARK.map((id) => `:root[data-palette="${id}"] {\n${render(merged(id, "dark"))}\n}`),
];

const palettes = parts.join("\n\n") + "\n";
writeFileSync(join(here, "palettes.css"), palettes);

// --- assemble ---------------------------------------------------------------

let page = read(join(here, "src/page.html"));
page = page.replace("<!-- PALETTES -->", `<style>\n${palettes}</style>`);

const shots = new Map();
for (const file of readdirSync(join(here, "shots")).filter((f) => f.endsWith(".png"))) {
  const b64 = readFileSync(join(here, "shots", file)).toString("base64");
  shots.set(`shots/${file}`, `data:image/png;base64,${b64}`);
}

const inlined = page.replace(/src="(shots\/[^"]+)"/g, (whole, path) => {
  const uri = shots.get(path);
  if (!uri) throw new Error(`missing screenshot: ${path}`);
  return `src="${uri}"`;
});

// A published artifact is sandboxed and cannot hand the viewer a file, so its
// call to action points at the project instead of a relative installer that
// would silently do nothing.
const RELEASES = "https://github.com/infonality/onionskin/releases";
writeFileSync(
  join(here, "artifact.html"),
  inlined
    .replace(
      '<a class="btn" href="Onionskin_0.1.0_x64_en-US.msi" download\n            >Windows installer <span class="size">3.4 MB</span></a\n          >',
      `<a class="btn" href="${RELEASES}" target="_blank" rel="noreferrer"\n            >Get the Windows installer <span class="size">3.4 MB</span></a\n          >`,
    )
    .replace(
      "Windows 10 and 11 · x64 · version 0.1.0<br />",
      "Windows 10 and 11 · x64 · version 0.1.0<br />",
    ),
);

// The artifact host wraps the fragment in its own document. The standalone
// file needs a real shell, with head content and body content on the right
// sides of </head> — otherwise the parser has to guess where the body starts.
const HEAD_END = '<header class="nav">';
const split = inlined.indexOf(HEAD_END);
if (split < 0) throw new Error("could not find the head/body boundary");

writeFileSync(
  join(here, "index.html"),
  [
    "<!doctype html>",
    '<html lang="en">',
    "<head>",
    '<meta charset="utf-8">',
    '<meta name="viewport" content="width=device-width, initial-scale=1">',
    '<meta name="description" content="Onionskin is a desktop Markdown editor with live preview: the Markdown syntax hides as you write and returns when the caret lands on it.">',
    inlined.slice(0, split).trim(),
    "</head>",
    "<body>",
    inlined.slice(split).trim(),
    "</body>",
    "</html>",
    "",
  ].join("\n"),
);

const kb = (s) => (Buffer.byteLength(s) / 1024).toFixed(0) + " KB";
console.log(`palettes.css   ${kb(palettes)}  (${overrides.size + 2} themes)`);
console.log(`index.html     ${kb(readFileSync(join(here, "index.html"), "utf8"))}`);
console.log(`artifact.html  ${kb(inlined)}`);
